// ESLint flat config for FS25 Farm Planner Web.
//
// This re-exports the flat config generated by the @nuxt/eslint module. That
// file (.nuxt/eslint.config.mjs) does not exist until `nuxt prepare` has run at
// least once (it is produced by the `postinstall` script). After install/build
// this import resolves and `withNuxt()` yields the project lint rules.
//
// Kept intentionally minimal and robust: additional FSD layer-boundary rules
// (ADR-F02) are layered on top in later stories (see plan H6.1).
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt()
